NUM_GPUS: 8
NUM_SHARDS: 1
OUTPUT_DIR: ""
RUN_N_TIMES: 1
MODEL:
  FROZEN: True
  TYPE: "base"
  KNN_LAMBDA: 0.5
  LINEAR:
    MLP_SIZES: []
SOLVER:
  SCHEDULER: "decay"
  WARMUP_EPOCH: 5
  TOTAL_EPOCH: 100
  LR_DECAY_SCHEDULE: [30, 60, 90]
  LR_DECAY_FACTOR: 0.1
  LOSS: "softmax"
  OPTIMIZER: "sgd"  # or "adamw"
  MOMENTUM: 0.9
  WEIGHT_DECAY: 0.0
  BASE_LR: 1.2
  LOG_EVERY_N: 10
  PATIENCE: 100
DATA:
  NAME: "imagenet"
  NUMBER_CLASSES: 1000
  MULTILABEL: False
  FEATURE: "random"
  BATCH_SIZE: 1024
  NUM_WORKERS: 32
  NO_TEST: True
  PIN_MEMORY: True