NUM_GPUS: 1
NUM_SHARDS: 1
OUTPUT_DIR: ""
RUN_N_TIMES: 1
MODEL:
  FROZEN: True
  TYPE: "joint"
  LINEAR:
    MLP_SIZES: []
DSTORE:
  FEATUREMAP_POOL: "max"
  NORM_TYPE: "L2NC"
SOLVER:
  SCHEDULER: "cosine"
  PATIENCE: 300
  LOSS: "softmax"
  OPTIMIZER: "sgd"  # or "adamw"
  MOMENTUM: 0.9
  WEIGHT_DECAY: 0.0001
  LOG_EVERY_N: 1
  LR_DECAY_SCHEDULE: [100, 200]  # for decay
  WARMUP_EPOCH: 5
  TOTAL_EPOCH: 100
DATA:
  NAME: ""
  NUMBER_CLASSES: -1
  FEATURE: ""
  BATCH_SIZE: 1024