NUM_GPUS: 1
NUM_SHARDS: 1
OUTPUT_DIR: ""
RUN_N_TIMES: 5
MODEL:
  FROZEN: False
  TYPE: "joint"
  KNN_LAMBDA: 0.5
  LINEAR:
    MLP_SIZES: []
DSTORE:
  TOPK: 16
  TOPK_TYPE: None
  FEATUREMAP_POOL: "max"
  INDEX_FOLDER: ""
  USE_CACHE: True
SOLVER:
  SCHEDULER: "cosine"
  WARMUP_EPOCH: 5
  LR_DECAY_SCHEDULE: [100, 200]
  LR_DECAY_FACTOR: 0.1
  LOSS: "softmax"
  OPTIMIZER: "sgd"  # or "adamw"
  MOMENTUM: 0.9
  WEIGHT_DECAY: 0.0001
  LOG_EVERY_N: 10
  TOTAL_EPOCH: 300
  PATIENCE: 300
DATA:
  NAME: ""
  NUMBER_CLASSES: -1
  DATAPATH: ""
  FEATURE: "imagenet_supervised"
  BATCH_SIZE: 384
  NUM_WORKERS: 8