_BASE_: "../base-linear.yaml"
RUN_N_TIMES: 5
DATA:
  NAME: "StandfordDogs"
  NUMBER_CLASSES: 120
  MULTILABEL: False
MODEL:
  TYPE: "base"
  KNN_LAMBDA: 0.1
DSTORE:
  TOPK: 16
  TEMP: 0.1
SOLVER:
  BASE_LR: 0.001
  WEIGHT_DECAY: 0.0001